[tool.poetry]
name = "bitbucket-analyzer-sample"
version = "0.0.1"
package-mode = false

[tool.poetry.dependencies]
python = "3.11.7"
uvicorn = "0.27.1"
httpx = "^0.27.0"
python-dateutil = "^2.9.0.post0"
gitpython = "^3.1.43"
requests = "^2.32.3"
